### ISSUE TITLE
Packaged `patchperl` has no Devel::PatchPerl (or Module::Pluggable - doesn't work on modern Perls)

### ISSUE THREAD

**Issue by mohawk2** [gugod/patchperl-packing#11]
Thank you for Perlbrew, which is great! Sadly, it's currently not working in PDL's CI because there's no Devel::PatchPerl in the fatpacked script. I assume this is due to an error in the fatpacking process.

**Comment by DanielTStaal** [comment]
Just another request for this - I managed to work around since I had a patchperl on a different box from a recent install of perlbrew a few days ago, but at the moment the perlbrew install process is badly broken because of this.

**Comment by snobear** [comment]
Same. Is there a workaround, i.e. a way to have perlbrew install a pinned older version of patchperl?

cc @gugod

**Comment by mohawk2** [comment]
You can get the pre-broken version by snapshotting this repo from about 4 commits before current `master`. I haven't yet made such a change to benefit PDL's infrastructure. My only use for it is for "weird" Perls that have `quadmath` or `longdouble`, and I'm going to open an issue on https://github.com/shogo82148/actions-setup-perl to ask them to add those so I can drop perlbrew from my CI entirely.

**Comment by gugod** [comment]
Thanks, I didn't notice this. This repos is mostly automated but I wasn't sure what breaks the automation.

**Comment by gugod** [comment]
The previous commit dc1074880d9d78a18592516c25b95911a5039cf6 removed almost all lines from the result (`patchperl` script) and is obviously a mistake. I'll revert that commit for now.

**Comment by gugod** [comment]
> The previous commit [dc10748](https://github.com/gugod/patchperl-packing/commit/dc1074880d9d78a18592516c25b95911a5039cf6) removed almost all lines from the result (`patchperl` script) and is obviously a mistake. I'll revert that commit for now.

It looks like that's insufficient. The first bad commit was 19473aa8c928d76be270c8ce017e2e7d8a6c862c and all commits after that basically became pointless. I'll just rebuild everything once.

**Comment by gugod** [comment]
> It looks like that's insufficient. The first bad commit was [19473aa](https://github.com/gugod/patchperl-packing/commit/19473aa8c928d76be270c8ce017e2e7d8a6c862c) and all commits after that basically became pointless. I'll just rebuild everything once.

I manually rebuild the fatpacked `patchperl` script and the commit 
1f2f7cf6843b0e9c2e8d0756dcc91b45d19e20e7 should be a good one.

**Comment by oalders** [comment]
Thanks @gugod!

**Comment by gugod** [comment]
my machine that runs the automation (cronjob) ran out of disk space somehow.. which is probably why the fatpacking process failed to include `PatchPerl.pm` and many other `.pm` files... I'll have do some cleanup work... but meanwhile I've disable that cronjob for now. So at least it shouldn't be automatically broken (?) again.

**Comment by mohawk2** [comment]
@gugod I've just tried re-running one of the PDL CI runs that was broken by this problem. It still fails, complaining Module::Pluggable isn't there. Unless I'm doing something wrong, this isn't fixed yet.

Meanwhile, the new job that just ran after adding DrHyde's workaround *is* working.

**Comment by mohawk2** [comment]
*Now* it's working: the incantation I had to put in before the running of `perlbrew` is:

```
yes|sudo perl -MCPAN -e 'CPAN::Shell->notest("install","Devel::PatchPerl")'
```

**Comment by gugod** [comment]
> @gugod I've just tried re-running one of the PDL CI runs that was broken by this problem. It still fails, complaining Module::Pluggable isn't there. Unless I'm doing something wrong, this isn't fixed yet.

Thank you for this info, I believe that's due to the fact that the 'patchperl' in this repo  is (has been) prepared in a perl-5.8 environment and Module::Pluggable has been in core, but no longer the case. You are probably using some recent perl version that shipped without Module::Pluggable.

This means that for I need to adjust the procedure in `build.sh` to also ensure Module::Pluggable (and perhaps other dependencies) are fatpacked together.

**Comment by gugod** [comment]
> @gugod I've just tried re-running one of the PDL CI runs that was broken by this problem. 

Is PDL CI publicly available? I would like to briefly reproduce the issue so I could confirm my fix would be working for you instead of only preparing a fix based on some theories in my head. Or If you could provide me the perl version that runs `patchperl`, that should be enough.

**Comment by mohawk2** [comment]
@gugod https://github.com/PDLPorters/pdl/blob/master/.github/workflows/ci.yml#L205-L233

It'll be a recent Perl since it's on `ubuntu-latest`.

**Comment by DrHyde** [comment]
> @gugod I've just tried re-running one of the PDL CI runs that was broken by this problem. It still fails, complaining Module::Pluggable isn't there. Unless I'm doing something wrong, this isn't fixed yet.
> 
> ~Meanwhile, the new job that just ran after adding DrHyde's workaround _is_ working~. **EDIT** No, it's still not. Even saying `notest installl` to CPAN, it's running the tests and failing.

Module::Pluggable has a bug in its tests that only shows up if you run the tests as root: https://github.com/simonwistow/Module-Pluggable/issues/27

**Comment by mohawk2** [comment]
@snobear @DanielTStaal The most recent above-linked commit shows the modification to get perlbrew running for recent Perls.

I'm sure gugod is close to making this whole thing work seamlessly again, but in the meantime the worked-around perlbrew helped me catch then fix quite a subtle but serious problem that coincidentally got introduced (by me, sigh) in PDL in just the week it's been problematic.

**Comment by gugod** [comment]
It looks like there are 2 parts of the problem of "Module XYZ is not in the fatpacked version of patchperl".

I've decided to start depending on at least perl-5.38.2 to prepare the fatpacked `patchperl` script, that solves one part of the problem.

The 2nd part of the problem is about the modules that are installed together with system perl -- usually the ones in the `Module::CoreList` -- the output of `corelist -v 5.38.2`, that is.

On Ubuntu 22.04, we would need *both* of the following packages to run the fatpacked patchperl provided in this repo:

- `perl-base`
- `perl-modules-5.34`

... and this is because `patchperl` (indirectly) requires `PerlIO`, a core module, and in Ubuntu, PerlIO is not part of `perl-base` but in `perl-modules-$version` instead.

I could try to see how PerlIO is required by patchperl and decide if any more resolutions can be implemented in this repo... but meanwhile, for the setup step of PDL CI, I'd suggest a few possible workarounds:


* If patchperl is needed -- this is often required if you are building some old version of perl on modern systems (what patchperl is designed for):
    *  do a `sudo apt install perl-modules-5.34` to bring in all the core modules.

* If patchperl turns out to be not needed -- this is generally the case for recent versions of perl on recent version of OSes
     * Add `--no-patchperl`. For example: `perlbrew install --no-patchperl perl-5.40.0`


I guess we could explore the option to make `--no-patchperl` default or make perlbrew smart about whether `patchperl` might end patching nothing and just don't invoke it in the first place.

**Comment by DrHyde** [comment]
I'm not keen on making `--no-patchperl` the default, as I would expect that to break many peoples' existing setups. It would perhaps be reasonable to make it the default for builds of the most recent release of perl, and maybe the one before that, but any smarter than that risks just duplicating Devel::PatchPerl in the smartness.

Devel::PatchPerl has a PerlIO-related patch for perl 5.8.9, but that aside any use of PerlIO is in one of D::PP's dependencies. I guess the way to find that would be to put a `\&subref` in `@INC` that spits out stack traces as it loads modules.

On modern perl, D::PP's only non-core deps are Module::Pluggable and File::pushd, and I expect those could be fairly easily worked around with patches in D::PP - I wonder, would @Bingos be amenable to that?

**Comment by DrHyde** [comment]
Oh, another point - `PerlIO` is Magical. It will get loaded if you do something like `open(my $fh, "<:encoding ...`. It doesn't even have to be mentioned by name in the code. But it _does_ get loaded via `@INC` in the normal way:

```
$ perl -E 'unshift @INC, sub { say $_[1] }; open(my $fh, "<:encoding(UTF-8)", "yummy-characters")'
PerlIO.pm
PerlIO/encoding.pm
...
```

**Comment by mohawk2** [comment]
As an alternative to using the web download in CI, here is what I'm now using for the "weird Perls" thing - it's using the Ubuntu packaged version. @DrHyde this might be useful for you, too. It even has `ccache` so it compiles about twice as fast.

```yaml
  weird-perls:
    runs-on: "ubuntu-latest"
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    strategy:
      matrix:
        weirdness: [ 'uselongdouble', 'usequadmath' ]
    name: Perl with ${{ matrix.weirdness }}
    steps:
      - uses: actions/checkout@v4
      - uses: Chocobo1/setup-ccache-action@v1
        with:
          override_cache_key: ccache-v0.0-ubuntu-${{ matrix.weirdness }}
      - name: Build perl ...
        env:
          MAKEFLAGS: --jobs=4
        run: |
            sudo apt-get update && sudo apt-get install perlbrew
            perlbrew init
            perlbrew install --notest -D ${{ matrix.weirdness }} perl-5.40.0 --as perl-5.40.0-${{ matrix.weirdness }} || (cat ~/perl5/perlbrew/build.perl-5.40.0.log; false)
      - name: run tests
        env:
          PERL_USE_UNSAFE_INC: 0
          HARNESS_OPTIONS: j4
          MAKEFLAGS: --jobs=4
        run: |
            source ~/perl5/perlbrew/etc/bashrc
            perlbrew switch perl-5.40.0-${{ matrix.weirdness }}
            perlbrew install-cpanm
            perl -V|grep archname
            (cpanm -n ExtUtils::MakeMaker Devel::CheckLib File::Which && cpanm -n --installdeps .) || ( cat ~/.cpanm/build.log && false )
            perl Makefile.PL
            make test
```
